name: galleria
description: "Photo gallery app. This is a technical assessment for a Junior Flutter Engineer role at ChigiSoft"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^11.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  uicons: ^1.0.1
  image_picker: ^1.2.1
  gal: ^2.3.2
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  logger: ^2.6.2
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  json_serializable: ^6.11.2
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #